apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: bidw-subscription-hpa
  namespace: high5-bidw-ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bidw-subscription
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80